services:
  envoy:
    image: envoyproxy/envoy:v1.35.3
    network_mode: host
    user: "1337:1337"
    volumes:
      - ./ctf_proxy/proxy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./interceptor/wasm:/etc/envoy/wasm:ro
      - ./logs:/var/log/envoy   
    command: ["-c", "/etc/envoy/envoy.yaml"]
    restart: unless-stopped

  logs-processor:
    build:
      context: .
      dockerfile: Dockerfile.logs-processor
    user: "1337:1337"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./logs-archive:/app/logs-archive
    environment:
      - TAP_FOLDER=/app/logs/tap
      - HTTP_ACCESS_LOG=/app/logs/http_access.log
      - DB_FILE=/app/data/proxy_stats.db
      - ARCHIVE_FOLDER=/app/logs-archive
      - CONFIG_FILE=/app/data/config.yml
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - envoy

  ui:
    build:
      context: .
      dockerfile: Dockerfile.logs-processor
    user: "1337:1337"
    volumes:
      - ./data:/app/data
      - ./logs-archive:/app/logs-archive
    environment:
      - DB_FILE=/app/data/proxy_stats.db
      - CONFIG_FILE=/app/data/config.yml
      - ARCHIVE_FOLDER=/app/logs-archive
      - PYTHONUNBUFFERED=1
    command: ["ctf-proxy-dashboard", "--config", "/app/data/config.yml", "--db", "/app/data/proxy_stats.db"]
    restart: no

  dashboard-backend:
    build:
      context: .
      dockerfile: Dockerfile.logs-processor
    user: "1337:1337"
    volumes:
      - ./data:/app/data
      - ./logs-archive:/app/logs-archive
    environment:
      - DB_FILE=/app/data/proxy_stats.db
      - CONFIG_FILE=/app/data/config.yml
      - ARCHIVE_FOLDER=/app/logs-archive
      - PYTHONUNBUFFERED=1
    command: ["python", "-m", "ctf_proxy.dashboard.main", "--config", "/app/data/config.yml", "--db", "/app/data/proxy_stats.db", "--host", "0.0.0.0", "--port", "48955"]
    ports:
      - "127.0.0.1:48955:48955"
    restart: unless-stopped
    depends_on:
      - envoy
