services:
  envoy:
    image: envoyproxy/envoy:v1.35.3
    network_mode: host
    user: "1337:1337"
    volumes:
      - ./ctf_proxy/proxy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./interceptor/wasm:/etc/envoy/wasm:ro
      - ./logs:/var/log/envoy   
    command: ["-c", "/etc/envoy/envoy.yaml"]
    restart: unless-stopped

  logs-processor:
    build:
      context: .
      dockerfile: Dockerfile.logs-processor
    user: "1337:1337"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./logs-archive:/app/logs-archive
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - envoy

  dashboard-backend:
    build:
      context: .
      dockerfile: Dockerfile.logs-processor
    user: "1337:1337"
    volumes:
      - ./data:/app/data
      - ./logs-archive:/app/logs-archive
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG_PATH=/app/data/config.yml
      - DB_PATH=/app/data/proxy_stats.db
    command: ["gunicorn", "ctf_proxy.dashboard.app:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:48955", "--timeout", "120", "--access-logfile", "-", "--error-logfile", "-"]
    ports:
      - "127.0.0.1:48955:48955"
    restart: unless-stopped
    depends_on:
      - envoy
